version: "3"

networks:
  test:
    external:
      name: gotask_default

services:
    data:
      build: ./.docker/.
      ports:
      - "8000:80"
      volumes:
      - .:/var/www/html/
      - "./.docker/php.ini:/usr/local/etc/php/php.ini"
      networks:
      - test

    db:
      image: mysql:5.7
      ports:
      - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: laravel
        MYSQL_USER: elbit
        MYSQL_PASSWORD: secret
      volumes:
      - ./.docker/dump:/docker-entrypoint-initdb.d/
      - ./persistent:/var/lib/mysql/
      - ./db/hosts:/var/tmp/hosts/
      networks:
      - test